# Generated using these functions in crypto.py:
# generate_keypair, and then encoded with serialize_key
#
# These are ECC keys exported in the DEM format and then encoded with base64
SERVER_PUBLIC_KEY = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdzDLAhsrtmsFRho/WTE75MBps9na5YhqPqbnmcZinusQz1chO0glIE/rql7uuCrEzm9GhZc/SRWzHV9ogDwO+Q=="
SERVER_PRIVATE_KEY = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgA519IBR6jZwfYqdRuVP5t0bHUKQbBis80UlhjjSW7nyhRANCAAR3MMsCGyu2awVGGj9ZMTvkwGmz2drliGo+pueZxmKe6xDPVyE7SCUgT+uqXu64KsTOb0aFlz9JFbMdX2iAPA75"

CLIENT_PUBLIC_KEY = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvSDj3LtVV2zoVKs8/gbLgiJrjOlqSUJPotgXTrN7L7DBaOB6gNyr8aPi7j9cGcEfFRyBOQh/ntZLWEVfoFi+Fg=="
CLIENT_PRIVATE_KEY = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgV2/cJizAizm/9gGlHca91LAVHxN19jJEESWiEs9qZSihRANCAAS9IOPcu1VXbOhUqzz+BsuCImuM6WpJQk+i2BdOs3svsMFo4HqA3Kvxo+LuP1wZwR8VHIE5CH+e1ktYRV+gWL4W"


